[project]
name = "glamira-ingestion"
version = "0.1.0"
description = "Data ingestion pipeline for Glamira 32GB dataset"
authors = [
    {name = "Data Engineer"}
]
requires-python = "^3.10"
dependencies = [
    "polars (>=1.41.2,<2.0.0)",
    "pymongo (>=4.17.0,<5.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "ip2location (>=8.11.0,<9.0.0)",
    "aiohttp (>=3.14.1,<4.0.0)",
    "bs4 (>=0.0.2,<0.0.3)",
    "fake-useragent (>=2.2.0,<3.0.0)",
    "curl-cffi (>=0.15.0,<0.16.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
package-mode = false